# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 786764498404eb1c7b6b59ec036e116457ac3c381244f531a16a47fa975d2ac2ae766f1c66940f2456796c19ddf1e88b8fc1dc80c2eeec081d3cc89175df2fc5

test:
  secret_key_base: cd82611e6a5f4756a76998467a197eb4c943f3ff8881eae841f688693b437c156379fcb3728c8c744568be33773b974b2b6e835f31a05a0d68a2a2d4b1e74604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
